# Use postgres/example user/password credentials
version: "3.4"

services:
  postgres:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    healthcheck:
      test: echo "SELECT 1" | psql --username postgres --quiet --no-align --tuples-only | grep -q 1 || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: library/redis:6.2-alpine
    command: redis-server --port 6380 --appendonly yes
    healthcheck:
      test: redis-cli -h localhost -p 6380 ping | grep -q PONG || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  vault:
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault_secret_token1234

  build:
    image: bluetab/elixir:1.18.1-otp-27-slim-20250107094721
    command: ci/build.sh
    environment:
      APP_VERSION: "${APP_VERSION}"
      HOME: /tmp # CURRENT_UID doesn't have a home
      MIX_ENV: prod
      MIX_HOME: /code/.mix
    user: ${CURRENT_UID-0:0}
    working_dir: /code
    volumes:
      - "${CI_PROJECT_DIR}:/code"

  test:
    image: bluetab/elixir:1.18.1-otp-27-slim-20250107094721
    command: ci/test.sh
    environment:
      HOME: /tmp # CURRENT_UID doesn't have a home
      MIX_ENV: test
      MIX_HOME: /code/.mix
    working_dir: /code
    user: ${CURRENT_UID-0:0}
    volumes:
      - "${CI_PROJECT_DIR}:/code"
    depends_on:
      - postgres
      - redis
      - vault

  service:
    image: ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_USER: postgres
      GUARDIAN_SECRET_KEY: topsecret
      MILVUS_HOST: milvus
      MILVUS_PORT: 9091
      REDIS_HOST: redis
      REDIS_PORT: "6380"
      VAULT_ADDR: http://vault:8200/
      VAULT_SECRETS_PATH: secret/data/cx/
      VAULT_TOKEN: vault_secret_token1234
    depends_on:
      - postgres
      - redis
      - vault

  acceptance:
    image: bluetab/wait-for:20190507133127
    command: service:4015 -t 30 -- curl --silent service:4015/api/ping
    depends_on:
      - service
